# Site settings
title: Brandon Stevenson
email: your.email@example.com
description: >-
  Physicist and Software Developer specializing in machine learning and data analysis.
language: en
baseurl: ""
url: "https://jbrandons.github.io"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Social media usernames (optional)
github_username: JBrandonS
linkedin_username: JBrandonS

# Navigation
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
